### ISSUE TITLE
Pause and Resume issue?

### ISSUE THREAD

**Issue by FazliMolaJan** [1612052/Zecorder#6]
Thanks for the amazing library, I would like to ask that how to pause and resume the recording during the screen recording?

**Comment by chienpm304** [comment]
Sorry for lately response. 
I wrote the 2 funcs **pauseScreenRecord()** and **resumeScreenRecord()** in RecordingService.java.
By the way, check the MediaMuxerWrapper.java for more detail regarding to controlling the media encoder.
